# Generated by Django 3.1.1 on 2023-06-20 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20230620_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.product', verbose_name='продукт')),
            ],
        ),
    ]
